# .goreleaser.yml
project_name: rdsinstance

before:
  hooks:
    - go mod download

builds:
  - main: PostgresDatabase/postgresDatabase.go
    binary: PostgresDatabase/postgresDatabase
    goos: [linux]
    goarch: [amd64]

archive:
  format: binary

release:
  disable: true
