# .goreleaser.yml
project_name: forge

before:
  hooks:
    - go mod download

builds:
  - main: aws/CloudFormation/ApiKey/apiKey.go
    binary: apiKey
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/CogCondPreAuthSettings/cogCondPreAuthSettings.go
    binary: cogCondPreAuthSettings
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/CognitoIdentityProvider/cognitoIdentityProvider.go
    binary: cognitoIdentityProvider
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/CognitoUserPoolClientSettings/cognitoUserPoolClientSettings.go
    binary: cognitoUserPoolClientSettings
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/CognitoUserPoolDomain/cognitoUserPoolDomain.go
    binary: cognitoUserPoolDomain
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/DbInstanceResourceId/dbInstanceResourceId.go
    binary: dbInstanceResourceId
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/DnsCertificate/dnsCertificate.go
    binary: dnsCertificate
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/DnsCertificateCheck/dnsCertificateCheck.go
    binary: dnsCertificateCheck
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/EcrCleanup/ecrCleanup.go
    binary: ecrCleanup
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/ForgeResources/forgeResources.go
    binary: forgeResources
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/ListenerRuleSwapper/listenerRuleSwapper.go
    binary: listenerRuleSwapper
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/S3Cleanup/s3Cleanup.go
    binary: s3Cleanup
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/Sequence/sequence.go
    binary: sequence
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/SequenceValue/sequenceValue.go
    binary: sequenceValue
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudwatchLogs/LogsMaintenance/logsMaintenance.go
    binary: logsMaintenance
    goos: [linux]
    goarch: [amd64]
  - main: aws/CodeCommit/PipelineTrigger/pipelineTrigger.go
    binary: pipelineTrigger
    goos: [linux]
    goarch: [amd64]
  - main: aws/Cognito/CogCondPreAuth/cogCondPreAuth.go
    binary: cogCondPreAuth
    goos: [linux]
    goarch: [amd64]

archive:
  format: binary

release:
  disable: true
