# .goreleaser.yml
project_name: forge

before:
  hooks:
    - go mod download

builds:
  - main: aws/CloudFormation/DnsCertificate/dnsCertificate.go
    binary: DnsCertificate/dnsCertificate
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/DnsCertificateCheck/dnsCertificateCheck.go
    binary: DnsCertificateCheck/dnsCertificateCheck
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/DnsCertificateRecordSetGroup/dnsCertificateRecordSetGroup.go
    binary: DnsCertificateRecordSetGroup/dnsCertificateRecordSetGroup
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/DnsCertificateWaitSNSTrigger/dnsCertificateWaitSNSTrigger.go
    binary: DnsCertificateWaitSNSTrigger/dnsCertificateWaitSNSTrigger
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/S3Cleanup/s3Cleanup.go
    binary: S3Cleanup/s3Cleanup
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/Sequence/sequence.go
    binary: Sequence/sequence
    goos: [linux]
    goarch: [amd64]
  - main: aws/CloudFormation/SequenceValue/sequenceValue.go
    binary: SequenceValue/sequenceValue
    goos: [linux]
    goarch: [amd64]

archive:
  format: binary

release:
  disable: true
